name: experiment

on:
  pull_request:
  push:
    branches: [ '**' ]

jobs:
  experiment:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v34

    - name: List all changed files
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed"
        done
    
    - name: Build nextflow schemas
      uses: viash-io/viash-actions/build_nextflow_schemas@build_nextflow_schemas
      with:
        workflows: workflows
        token: ${{ secrets.GTHB_PAT }}
        tools_version: 'main_build'
    
    - uses: actions/checkout@v3
      with:
        repository: openpipelines-bio/website
        path: openpipelines-website
        
    - uses: actions/checkout@v3
      with:
        repository: openpipelines-bio/openpipelines
        path: openpipelines

    - uses: viash-io/viash-actions/generate_documentation_qmd@generate_documentation_qmd
      with:
        input_dir: openpipelines
        output_dir: openpipelines-bio/website/components
        dest_path: "{type}s/{namespace}/{name}.qmd"
        git_repo: openpipelines-bio/openpipelines
        
