name: experiment

on:
  pull_request:
  push:
    branches: [ '**' ]

jobs:
  experiment:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0


    - uses: viash-io/viash-actions/setup@v1.0.0

    - id: ns_list
      uses: viash-io/viash-actions/ns-list@improve_ns_list
      with:
        query: "step[12]"
        src: src
        platform: docker
        config_mod: ".functionality.version := '0.10.0'"
        format: json
        parse_argument_groups: true

    - run: |
        # do something with the output yaml
        cat | jq -c '[ .[] | { "name": .functionality.name, "namespace": .functionality.namespace, "config": .info.config } ]' << HERE
        ${{steps.ns_list.outputs.output}}
        HERE

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v34

    - name: List all changed files
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed"
        done