functionality:
  name: step2
  description: |
    This is the description that never ends.
      §1234567890'^
      °+"*ç%&/()=?`$"""'''@\\//\/
    \n\r\t\s\
  usage: |
    This is the description that never ends.
      §1234567890'^
      °+"*ç%&/()=?`$"""'''@\\//\/
    \n\r\t\s\
  argument_groups:
    - name: Input
      arguments:
        - name: "--input1"
          type: file
          example: input1.txt
          required: true
        - name: "--input2"
          type: file
          required: true
          example: input2.txt
        - name: "--optional"
          type: file
          required: false
          example: optional.txt
    - name: outputs
      arguments:
        - name: "--output1"
          type: file
          required: true
          example: output1.txt
        - name: "--output2"
          type: file
          required: true
          example: output2.txt
    - name: other arguments
      arguments:
        - name: "--default_arg"
          type: string
          description: |
            This is the description that never ends.
              §1234567890'^
              °+"*ç%&/()=?`$"""'''@\\//\/
            \n\r\t\s\
          # TODO: fix single quotes
          default: |
            This is the description that never ends.
              §1234567890^
              °+"*ç%&/()=?`$"""@\\//\/
            \n\r\t\s\
        - name: "--example"
          type: string
          example: |
            This is the description that never ends.
              §1234567890'^
              °+"*ç%&/()=?`$"""'''@\\//\/
            \n\r\t\s\
  resources:
    - type: bash_script
      path: script.sh
platforms:
  - type: native
  - type: docker
    image: nextflow/bash:latest
  - type: nextflow
